// Converts the official CorelDRAW SVG exports into inline-ready path markup.
// fil0 is the NB mark, fil1 the NUVENE BEAUTY wordmark.
// Run: node scripts/build-logos.mjs
import { readFileSync, writeFileSync } from "node:fs";

const SRC = "../nuvenebeauty.com/LOGOS/SVG";
const files = {
  LOGO_ICON: `${SRC}/ICON/ICON COLORED.svg`,
  LOGO_HORIZONTAL: `${SRC}/SECONDARY LOGO/SECONDARY LOGO COLORED.svg`,
  LOGO_STACKED: `${SRC}/PRIMARY LOGO/PRIMARY LOGO COLORED.svg`,
};

function convert(svg) {
  const viewBox = svg.match(/viewBox="([^"]+)"/)[1].trim();
  const paths = svg.match(/<path\b[^>]*\/>/g) ?? [];
  const body = paths
    .map((p) =>
      p
        .replace(/\s*class="fil0"/, ' style="fill:var(--logo-mark,currentColor)"')
        .replace(/\s*class="fil1"/, ' style="fill:var(--logo-word,currentColor)"'),
    )
    .join("");
  if (/class=/.test(body)) throw new Error("unmapped fill class");
  return { viewBox, body };
}

const out = Object.entries(files).map(([name, file]) => {
  const { viewBox, body } = convert(readFileSync(file, "utf8"));
  return `export const ${name} = {\n  viewBox: ${JSON.stringify(viewBox)},\n  body: ${JSON.stringify(body)},\n} as const;\n`;
});

writeFileSync(
  "src/components/brand/nuvene-logo-paths.ts",
  `// Generated by scripts/build-logos.mjs from the official logo SVGs. Do not edit.\n\n${out.join("\n")}`,
);

// Favicon: the NB mark in sage, centred on a square canvas. Literal fill,
// since some favicon renderers ignore CSS custom properties.
const icon = convert(readFileSync(files.LOGO_ICON, "utf8"));
const [, , w, h] = icon.viewBox.split(" ").map(Number);
const pad = Number(((w - h) / 2).toFixed(2));
const sageBody = icon.body.replaceAll("var(--logo-mark,currentColor)", "#708E74");
writeFileSync(
  "src/app/icon.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 ${-pad} ${w} ${w}">${sageBody}</svg>\n`,
);
console.log("logos written");
